- name: Install required packages
  package:
    name: zsh
    state: present
  become: yes
  tags:
    - install

- name: Ensure zplug is in place
  git:
    repo: "https://github.com/zplug/zplug"
    dest: "{{ home_dir }}/.zplug"
    update: no

- name: Link zsh files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ home_dir }}/{{ item | basename }}"
    state: link
    force: yes
  loop:
    - zsh/.zprofile
    - zsh/.zshenv
    - zsh/.zshrc

- name: Ensure config dir exits
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Link starship config
  file:
    src: "{{ role_path }}/files/starship.toml"
    path: "{{ config_dir }}/starship.toml"
    state: link
    force: yes
