- name: Install required packages
  package:
    name: zsh
    state: present
  become: yes
  tags:
    - install

- name: Ensure zplug is in place
  git:
    repo: "https://github.com/zplug/zplug"
    dest: "{{ home_dir }}/.zplug"
    update: no

- name: Copy zsh files
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/{{ item | basename }}"
  loop:
    - zsh/.zprofile
    - zsh/.zshenv
    - zsh/.zshrc

- name: Copy starship config
  copy:
    src: starship.toml
    dest: "{{ config_dir }}/starship.toml"
