- name: Install required packages
  package:
    name:
      - zsh
      - starship
    state: present
  tags:
    - install

- name: Copy zsh files
  copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/{{ item | basename }}"
  loop:
    - zsh/.zprofile
    - zsh/.zshenv
    - zsh/.zshrc

- name: Copy starship config
  copy:
    src: starship.toml
    dest: "{{ config_dir }}/starship.toml"
