- name: My Configuration
  hosts: localhost
  vars:
    - home_dir: "{{ ansible_env.HOME }}"
    - src_dir: "{{ ansible_env.HOME }}/src"
    - data_dir: "{{ ansible_env.HOME }}/.local/share"
    - config_dir: "{{ ansible_env.HOME }}/.config"
  roles:
    - { role: shell, tags: ['shell'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: tools, tags: ['tools'] }
    - { role: desktop, tags: ['desktop'] }
