- name: Install packages from arch repos
  tags: 
    - install
  pacman:
    name:
      - sway
      - swayidle
      - waybar
      - mako
      - mpd

      # utilities
      - grim
      - slurp
      - brightnessctl
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-jack
      - pulseaudio-bluetooth
      - udisks2
      - libnotify
      - wl-clipboard

      # apps
      - kitty
      - chromium
      - imv
      - mpv

      # tui & cli
      - mpc
      - ranger

      # fonts
      - ttf-fira-code
      - ttf-nerd-fonts-symbols
      - nerd-fonts-fira-code
    state: present
  become: yes

- name: Install aur packages
  aur:
    name:
      - swaylock-effects
      - sway-launcher-desktop
      - grimshot
    state: present
