- name: Install packages from arch repos
  tags: 
    - install
  pacman:
    name:
      - sway
      - swayidle
      - waybar
      - mako
      - mpv
      - mpd
      - mpc

      # utilities
      - grim
      - slurp
      - brightnessctl
      - pulseaudio
      - libnotify
      - wl-clipboard

      # apps
      - kitty
      - chromium
      - qutebrowser

      # fonts
      - ttc-iosevka
      - ttf-fira-code
      - ttf-nerd-fonts-symbols
    state: present
  become: yes

- name: Install aur packages
  aur:
    name:
      - swaylock-effects
      - sway-launcher-desktop
      - grimshot
    state: present
