- name: Install packages from arch repos
  tags: 
    - install
  package:
    name:
      - sway
      - swayidle
      - mako
      - waybar
      - slurp
      - grim
      - kitty
      - mpv
      - mpd
      - mpc
      - brightnessctl
    state: present

- name: Create the `aur_builder` user
  user:
    name: aur_builder
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    state: present
    validate: 'visudo -cf %s'

- name: Install `paru` using makepkg
  aur:
    name: paru
    state: present
    become: yes
    become_user: aur_builder

- name: Install aur packages
  aur:
    name:
      - swaylock-effects
      - sway-launcher-desktop
