- name: Install required packages
  package:
    name: "{{ lookup('vars', ansible_facts['os_family'] | lower ~ '_packages') }}"
    state: present
  tags:
    - install
  vars:
    archlinux_packages:
      - sway
      - swayidle
      - swaylock-effects
      - sway-launcher-desktop
      - mako
      - waybar
      - slurp
      - grim
      - kitty
      - mpv
      - mpd
      - mpc
      - brightnessctl

- name: Sync sway related config
  synchronize:
    src: "{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
  loop:
    - sway
    - mako
    - waybar

- name: Sync kitty config
  synchronize:
    src: kitty
    dest: "{{ config_dir }}/kitty"
