- include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - install

# - name: Ensure desktop related config dirs exist
#   file:
#     path: "{{ config_dir }}/{{ item }}"
#     state: directory
#   loop:
#     - sway
#     - swaylock
#     - waybar
#     - mako
#     - kitty

- name: Link desktop related config
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ config_dir }}/{{ item }}"
    state: link
    force: yes
  loop:
    - sway
    - swaylock
    - mako
    - waybar
    - kitty

- name: Copy chromium flags config
  file:
    src: chromium-flags.conf
    path: "{{ config_dir }}/chromium-flags"
    state: link
