#- import_tasks: "{{ lookup('vars', ansible_facts['os_family'] | lower) }}.yml"
- import_tasks: archlinux.yml

- name: Copy sway related config
  copy:
    src: "{{ item }}"
    dest: "{{ config_dir }}"
  loop:
    - sway
    - mako
    - waybar

- name: Copy kitty config
  copy:
    src: kitty
    dest: "{{ config_dir }}"
