- name: Install required packages from official repos
  pacman:
    name:
      - git
      - docker
      - docker-compose
      - python
      - nodejs
      - npm
      - yarn
      - github-cli
    state: present
  become: yes

- name: Install required packages from aur
  aur:
    name:
      - gitlab-glab-bin
