- include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
  tags:
    - install

- name: Ensure git config dir exists
  file:
    path: "{{ config_dir }}/git"
    state: directory

- name: Ensure user name and email in git config
  blockinfile:
    path: "{{ config_dir }}/git/config"
    marker_end: "end"
    marker_begin: "begin"
    marker: "# @@managed by ansible - {mark}@@"
    block: |
      [user]
      	email = "jmederosalvarado@gmail.com"
      	name = "Jorge Mederos Alvarado"
