- name: Install required packages
  package:
    name:
      - git
      - docker
    state: present
  become: yes
  tags:
    - install

- name: Copy git config
  copy:
    src: git
    dest: "{{ config_dir }}"
