- name: Install required packages
  package:
    name: "{{ lookup('vars', ansible_facts['os_family'] | lower ~ '_packages') }}"
    state: present
  tags:
    - install
  vars:
    archlinux_packages:
      - git

- name: Copy git config
  copy:
    src: git
    dest: "{{ config_dir }}"
