- name: Install nvim build dependencies
  package:
    name: "{{ lookup('vars', ansible_facts['os_family'] | lower ~ '_packages') }}"
    state: present
  become: yes
  vars:
    archlinux_packages:
      - base-devel
      - cmake
      - unzip
      - ninja
      - tree-sitter
      - curl

- name: Clone nvim
  git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ src_dir }}/community/nvim"
    depth: 1

- name: Build nvim from source
  make:
    chdir: "{{ src_dir }}/community/nvim"
    params:
      CMAKE_BUILD_TYPE: Release

- name: Install nvim
  make:
    target: install
    chdir: "{{ src_dir }}/community/nvim"
  become: yes

- name: Install nvim providers
  package:
    name: "{{ lookup('vars', ansible_facts['os_family'] | lower ~ '_packages') }}"
    state: present
  become: yes
  vars:
    archlinux_packages:
      - python-pynvim
