- name: Install nvim build dependencies
  package:
    name: "{{ lookup('vars', ansible_facts['os_family'] | lower ~ '_packages') }}"
    state: present
  become: yes
  vars:
    archlinux_packages:
      - base-devel
      - cmake
      - unzip
      - ninja
      - tree-sitter
      - curl

- name: Create temp dir for nvim source
  tempfile:
    state: directory
    prefix: neovim
  register: nvim_src
  become: yes

- name: Download nvim source
  unarchive:
    src: "https://github.com/neovim/neovim/archive/{{ nvim_commit }}.tar.gz"
    dest: "{{ nvim_src.path }}"
    remote_src: yes
  become: yes

- name: Build nvim from source
  make:
    chdir: "{{ nvim_src.path }}/neovim-{{ nvim_commit }}"
    params:
      CMAKE_BUILD_TYPE: Release
  become: yes

- name: Install nvim binary
  make:
    target: install
    chdir: "{{ nvim_src.path }}/neovim-{{ nvim_commit }}"
  become: yes
