- import_tasks: build.yml
  tags:
    - build
    - install

- name: Ensure Packer is in place
  git:
    dest: "{{ data_dir }}/nvim/site/pack/packer/start/packer.nvim"
    repo: "https://github.com/wbthomason/packer.nvim"
    update: no

- name: Ensure nvim config dir exits
  file:
    path: "{{ config_dir }}/nvim"
    state: directory

- name: Link nvim config
  file:
    src: "{{ role_path }}/files/{{ item }}"
    path: "{{ config_dir }}/nvim/{{ item }}"
    state: link
    force: yes
  loop:
    - lua
    - init.lua
    - config
    - coc-settings.json
